# Generated by Django 4.0.4 on 2022-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
